/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as protectedDashboardRouteImport } from './routes/(protected)/dashboard'
import { Route as protectedSendRouteImport } from './routes/(protected)/send'
import { Route as protectedTodosRouteImport } from './routes/(protected)/todos'
import { Route as protectedSessionIndexRouteImport } from './routes/(protected)/session/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)
const protectedDashboardRoute = protectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedSendRoute = protectedSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedTodosRoute = protectedTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedSessionIndexRoute = protectedSessionIndexRouteImport.update({
  id: '/session/',
  path: '/session/',
  getParentRoute: () => protectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/dashboard': typeof protectedDashboardRoute
  '/send': typeof protectedSendRoute
  '/todos': typeof protectedTodosRoute
  '/session/': typeof protectedSessionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/dashboard': typeof protectedDashboardRoute
  '/send': typeof protectedSendRoute
  '/todos': typeof protectedTodosRoute
  '/session': typeof protectedSessionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(protected)/dashboard': typeof protectedDashboardRoute
  '/(protected)/send': typeof protectedSendRoute
  '/(protected)/todos': typeof protectedTodosRoute
  '/(protected)/session/': typeof protectedSessionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/send'
    | '/todos'
    | '/session/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/send'
    | '/todos'
    | '/session'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(protected)'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(protected)/dashboard'
    | '/(protected)/send'
    | '/(protected)/todos'
    | '/(protected)/session/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(protected)/dashboard': {
      id: '/(protected)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedDashboardRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/send': {
      id: '/(protected)/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof protectedSendRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/todos': {
      id: '/(protected)/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof protectedTodosRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/session/': {
      id: '/(protected)/session/'
      path: '/session'
      fullPath: '/session/'
      preLoaderRoute: typeof protectedSessionIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface protectedRouteRouteChildren {
  protectedDashboardRoute: typeof protectedDashboardRoute
  protectedSendRoute: typeof protectedSendRoute
  protectedTodosRoute: typeof protectedTodosRoute
  protectedSessionIndexRoute: typeof protectedSessionIndexRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedDashboardRoute: protectedDashboardRoute,
  protectedSendRoute: protectedSendRoute,
  protectedTodosRoute: protectedTodosRoute,
  protectedSessionIndexRoute: protectedSessionIndexRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  protectedRouteRoute: protectedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
